// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hginfezoozyzhkqejrhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnaW5mZXpvb3p5emhrcWVqcmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDIzMjksImV4cCI6MjA2NjAxODMyOX0.GvQLb4a2TaWnhtSBqgAnOxGO3E4lcvjinoYEexHZLdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);